apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-task-manager1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-task-manager1
  template:
    metadata:
      labels:
        app: student-task-manager1
    spec:
      containers:
        - name: student-task-manager1
          image: student-task-manager1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
