apiVersion: v1
kind: Service
metadata:
  name: student-task-manager-service
spec:
  type: NodePort
  selector:
    app: student-task-manager1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
